# Generated by Django 2.2 on 2019-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190710_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
