# Generated by Django 2.2 on 2019-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leads_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='LocationFromOther',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
