# Generated by Django 2.2 on 2019-07-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='valid',
            new_name='is_valid',
        ),
    ]
