# Generated by Django 2.2 on 2019-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20190718_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='password_change_request',
            field=models.BooleanField(default=False),
        ),
    ]
